/** Build a self-contained, shareable PK battle report. */
import { getAgentLabel } from "@/lib/custom-agents"
import { assignJudgeScoreSlots, contestantForJudgeScore } from "@/lib/pk-judge"
import type { PkRound } from "@/stores/pk-arena-store"

export interface PkReportArtifact {
  path: string
  /** UTF-8 HTML encoded as base64. Present only for a runnable single-file
   * artifact; keeping it encoded prevents contestant markup from escaping the
   * report document while it is being generated. */
  contentBase64?: string
}

function esc(raw: string): string {
  return raw
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
}

function formatMs(ms: number): string {
  const seconds = Math.round(ms / 1000)
  if (seconds < 60) return `${seconds}s`
  return `${Math.floor(seconds / 60)}m ${String(seconds % 60).padStart(2, "0")}s`
}

function diffStats(diff: string | null) {
  let added = 0
  let removed = 0
  for (const line of diff?.split("\n") ?? []) {
    if (line.startsWith("+") && !line.startsWith("+++")) added += 1
    if (line.startsWith("-") && !line.startsWith("---")) removed += 1
  }
  return { added, removed }
}

function renderDiff(diff: string | null, empty: string): string {
  if (!diff?.trim()) return `<p class="empty">${esc(empty)}</p>`
  return `<pre>${diff
    .split("\n")
    .map((line) => {
      const cls = line.startsWith("+")
        ? "add"
        : line.startsWith("-")
          ? "del"
          : line.startsWith("@@")
            ? "hunk"
            : ""
      return `<span class="line ${cls}">${esc(line || " ")}</span>`
    })
    .join("")}</pre>`
}

function runnableHtmlArtifact(
  artifacts: readonly PkReportArtifact[]
): PkReportArtifact | null {
  return (
    artifacts.find(
      (artifact) =>
        artifact.contentBase64 != null && /\.html?$/i.test(artifact.path)
    ) ?? null
  )
}

export function buildPkReportHtml(
  round: PkRound,
  artifactsBySlot: Record<string, PkReportArtifact[]>,
  locale = "zh-CN"
): string {
  const zh = locale.toLowerCase().startsWith("zh")
  const l = zh
    ? {
        title: "智能体 PK 战报",
        status: "状态",
        finished: "已结束",
        running: "进行中",
        ready: "就绪",
        contestants: "参赛智能体",
        duration: "总用时",
        generated: "生成时间",
        ranking: "比赛结果",
        agent: "智能体",
        time: "用时",
        tokens: "输出 Token",
        turns: "轮次",
        changes: "代码变更",
        files: "文件",
        unavailable: "未提供",
        verdict: "裁判结论",
        details: "选手产出",
        outputFiles: "产出文件",
        diff: "代码 Diff",
        noFiles: "没有产出文件",
        noDiff: "没有可比较的代码变更",
        preview: "可运行预览",
        openRun: "新窗口运行",
        viewSource: "查看 HTML 源码",
        sandboxHint: "预览在隔离环境中运行",
        generatedBy: "由 Codeg 智能体 PK 竞技场生成",
      }
    : {
        title: "Agent PK Battle Report",
        status: "Status",
        finished: "Finished",
        running: "Running",
        ready: "Ready",
        contestants: "Contestants",
        duration: "Duration",
        generated: "Generated",
        ranking: "Results",
        agent: "Agent",
        time: "Time",
        tokens: "Output tokens",
        turns: "Turns",
        changes: "Code changes",
        files: "Files",
        unavailable: "Not reported",
        verdict: "Judge verdict",
        details: "Contestant output",
        outputFiles: "Output files",
        diff: "Code diff",
        noFiles: "No output files",
        noDiff: "No comparable code changes",
        preview: "Live preview",
        openRun: "Open and run",
        viewSource: "View HTML source",
        sandboxHint: "Preview runs in an isolated sandbox",
        generatedBy: "Generated by Codeg Agent PK Arena",
      }

  const finished = round.contestants.every((c) =>
    ["done", "error", "canceled"].includes(c.status)
  )
  const statusText = finished
    ? l.finished
    : round.status === "ready"
      ? l.ready
      : l.running
  const duration = round.contestants.reduce<number | null>(
    (max, c) => (c.durationMs == null ? max : Math.max(max ?? 0, c.durationMs)),
    null
  )
  const scores = assignJudgeScoreSlots(
    round.judgeResult?.scores ?? [],
    round.contestants.filter((contestant) => contestant.status === "done")
  ).sort((a, b) => a.rank - b.rank)
  const scoreBySlot = new Map(
    scores.flatMap((score) =>
      score.slot == null ? [] : ([[score.slot, score]] as const)
    )
  )

  const rows = round.contestants
    .map((c, index) => {
      const stat = diffStats(c.diff)
      const score = scoreBySlot.get(c.slot)
      const artifacts = artifactsBySlot[String(c.slot)] ?? []
      const tokenText = c.usage?.tokensReported
        ? c.usage.outputTokens.toLocaleString(locale)
        : l.unavailable
      return `<tr>
        <td class="rank">${score ? `#${score.rank}` : String(index + 1).padStart(2, "0")}</td>
        <td><b>${esc(getAgentLabel(c.agentType))}</b>${c.label ? `<small>${esc(c.label)}</small>` : ""}</td>
        <td>${score ? `<strong class="score">${score.score}</strong>` : "—"}</td>
        <td>${c.durationMs == null ? "—" : formatMs(c.durationMs)}</td>
        <td>${tokenText}</td>
        <td>${c.usage?.turnCount ?? "—"}</td>
        <td><span class="plus">+${stat.added}</span> <span class="minus">−${stat.removed}</span></td>
        <td>${artifacts.length}</td>
      </tr>`
    })
    .join("")

  const judge = round.judgeResult
    ? `<section class="verdict">
        <div class="eyebrow">${l.verdict}</div>
        <h2>${esc(round.judgeResult.summary)}</h2>
        <div class="comments">${scores
          .map((score) => {
            const contestant = contestantForJudgeScore(score, round.contestants)
            return `<article><span>#${score.rank}</span><div><b>${esc(
              getAgentLabel(score.agentType)
            )}${contestant?.label ? ` · ${esc(contestant.label)}` : ""} · ${score.score}</b><p>${esc(score.comment)}</p></div></article>`
          })
          .join("")}</div>
      </section>`
    : ""

  const details = round.contestants
    .map((c) => {
      const artifacts = artifactsBySlot[String(c.slot)] ?? []
      const runnable = runnableHtmlArtifact(artifacts)
      const fileList = artifacts.length
        ? `<ul>${artifacts
            .map((artifact) => `<li>${esc(artifact.path)}</li>`)
            .join("")}</ul>`
        : `<p class="empty">${l.noFiles}</p>`
      const body = runnable
        ? `<div class="artifact-layout">
          <div class="artifact-files"><h3>${l.outputFiles}</h3>${fileList}</div>
          <div class="artifact-preview" data-artifact-html="${runnable.contentBase64}">
            <div class="preview-toolbar"><div><b>${l.preview}</b><small>${esc(runnable.path)} · ${l.sandboxHint}</small></div><button type="button" data-open-artifact>${l.openRun} ↗</button></div>
            <iframe title="${esc(getAgentLabel(c.agentType))} · ${l.preview}" sandbox="allow-scripts allow-pointer-lock" referrerpolicy="no-referrer"></iframe>
            <details class="source-disclosure"><summary>${l.viewSource}</summary><pre class="artifact-source"></pre></details>
          </div>
        </div>`
        : `<div class="detail-grid">
          <div><h3>${l.outputFiles}</h3>${
            artifacts.length ? fileList : `<p class="empty">${l.noFiles}</p>`
          }</div>
          <div><h3>${l.diff}</h3>${renderDiff(c.diff, l.noDiff)}</div>
        </div>`
      return `<details class="contestant-detail">
        <summary><span>${esc(getAgentLabel(c.agentType))}${c.label ? ` · ${esc(c.label)}` : ""}</span><span>${l.outputFiles} ${artifacts.length} · ${runnable ? l.preview : l.diff}</span></summary>
        ${body}
      </details>`
    })
    .join("")

  return `<!doctype html>
<html lang="${esc(locale)}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${esc(l.title)} · ${esc(round.task)}</title>
<style>
:root{--ink:#11110f;--paper:#f3f0e8;--card:#fffdf7;--line:#d8d2c5;--accent:#ffd84d;--muted:#6b675e;--green:#087b45;--red:#b42318}*{box-sizing:border-box}body{margin:0;background:#ddd8cc;color:var(--ink);font:14px/1.55 Inter,-apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC",sans-serif}.sheet{width:min(1180px,100%);margin:32px auto;background:var(--paper);box-shadow:0 24px 80px #302b2050}.masthead{position:relative;overflow:hidden;background:var(--ink);color:#fff;padding:52px 56px 46px}.masthead:after{content:"PK";position:absolute;right:22px;bottom:-82px;font:900 220px/1 Arial;color:#ffffff0b;letter-spacing:-20px}.brand{display:flex;align-items:center;gap:12px;font-size:12px;font-weight:700;letter-spacing:.16em;text-transform:uppercase}.brand i{display:block;width:28px;height:5px;background:var(--accent)}h1{position:relative;max-width:900px;margin:56px 0 42px;font-size:clamp(34px,5vw,68px);line-height:1.04;letter-spacing:-.045em}.meta{position:relative;display:grid;grid-template-columns:repeat(4,1fr);gap:24px;border-top:1px solid #ffffff28;padding-top:22px}.meta span{display:block;color:#aaa79f;font-size:11px;text-transform:uppercase;letter-spacing:.08em}.meta b{display:block;margin-top:3px;color:#fff;font-size:15px;letter-spacing:0}.content{padding:42px 56px 64px}.section-head{display:flex;align-items:end;justify-content:space-between;margin:0 0 14px}.section-head h2{margin:0;font-size:22px;letter-spacing:-.02em}.section-head span,.eyebrow{font-size:11px;font-weight:800;letter-spacing:.14em;text-transform:uppercase;color:var(--muted)}.table-wrap{overflow:auto;border:1px solid var(--line);background:var(--card)}table{width:100%;border-collapse:collapse;min-width:820px}th,td{padding:15px 14px;border-bottom:1px solid var(--line);text-align:left;white-space:nowrap}th{background:#ebe6da;color:var(--muted);font-size:10px;letter-spacing:.08em;text-transform:uppercase}tr:last-child td{border-bottom:0}.rank{font:800 18px ui-monospace,monospace}.score{display:inline-grid;place-items:center;min-width:42px;padding:3px 8px;background:var(--accent);font-size:17px}td small{display:block;color:var(--muted)}.plus{color:var(--green)}.minus{color:var(--red)}.verdict{margin:42px 0;padding:34px;border:1px solid var(--ink);background:var(--card)}.verdict h2{max-width:900px;margin:10px 0 26px;font-size:25px;line-height:1.35}.comments{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:12px}.comments article{display:flex;gap:12px;border-top:1px solid var(--line);padding-top:14px}.comments article>span{font:800 18px ui-monospace,monospace}.comments p{margin:5px 0 0;color:var(--muted)}.details{margin-top:42px}details{border-top:1px solid var(--line);background:var(--card)}details:last-child{border-bottom:1px solid var(--line)}summary{display:flex;justify-content:space-between;gap:20px;padding:18px 20px;cursor:pointer;font-weight:700}summary span:last-child{color:var(--muted);font-size:12px;font-weight:500}.detail-grid{display:grid;grid-template-columns:minmax(220px,.35fr) minmax(0,1fr);gap:24px;border-top:1px solid var(--line);padding:20px}.detail-grid h3,.artifact-layout h3{margin:0 0 10px;font-size:12px;text-transform:uppercase;letter-spacing:.08em}.detail-grid ul,.artifact-files ul{margin:0;padding-left:18px;word-break:break-all}.artifact-layout{display:grid;grid-template-columns:minmax(180px,.22fr) minmax(0,1fr);gap:20px;border-top:1px solid var(--line);padding:20px}.artifact-preview{min-width:0;border:1px solid var(--line);background:#fff}.preview-toolbar{display:flex;align-items:center;justify-content:space-between;gap:16px;padding:10px 12px;border-bottom:1px solid var(--line);background:#ebe6da}.preview-toolbar div{min-width:0}.preview-toolbar b,.preview-toolbar small{display:block}.preview-toolbar small{overflow:hidden;color:var(--muted);font-size:11px;text-overflow:ellipsis;white-space:nowrap}.preview-toolbar button{shrink:0;border:1px solid var(--ink);background:var(--ink);color:#fff;padding:6px 10px;cursor:pointer;font:700 12px/1 inherit}.artifact-preview iframe{display:block;width:100%;height:min(620px,68vh);border:0;background:#fff}.source-disclosure{border-top:1px solid var(--line)}.source-disclosure summary{padding:10px 12px;font-size:12px}.artifact-source{max-height:420px}.empty{color:var(--muted)}pre{max-height:560px;margin:0;overflow:auto;background:#171715;color:#d7d3ca;padding:16px;font:11px/1.55 ui-monospace,SFMono-Regular,Menlo,monospace}.line{display:block;white-space:pre}.line.add{background:#0c7b4530;color:#a9e6c5}.line.del{background:#b4231833;color:#ffb4ab}.line.hunk{color:#ffd84d}.footer{display:flex;justify-content:space-between;border-top:1px solid var(--line);margin-top:42px;padding-top:18px;color:var(--muted);font-size:12px}@media(max-width:720px){.sheet{margin:0}.masthead,.content{padding-left:22px;padding-right:22px}h1{margin:38px 0 30px}.meta{grid-template-columns:1fr 1fr}.detail-grid,.artifact-layout{grid-template-columns:1fr}.footer{display:block}}@media print{body{background:#fff}.sheet{width:100%;margin:0;box-shadow:none}details{break-inside:avoid}.masthead{-webkit-print-color-adjust:exact;print-color-adjust:exact}}
.preview-toolbar button{flex-shrink:0}
</style></head><body><main class="sheet">
<header class="masthead"><div class="brand"><i></i>Codeg · ${esc(l.title)}</div><h1>${esc(round.task)}</h1><div class="meta"><div><span>${l.status}</span><b>${statusText}</b></div><div><span>${l.contestants}</span><b>${round.contestants.length}</b></div><div><span>${l.duration}</span><b>${duration == null ? "—" : formatMs(duration)}</b></div><div><span>${l.generated}</span><b>${new Date().toLocaleString(locale)}</b></div></div></header>
<div class="content"><section><div class="section-head"><h2>${l.ranking}</h2><span>ROUND ${round.id}</span></div><div class="table-wrap"><table><thead><tr><th>#</th><th>${l.agent}</th><th>Score</th><th>${l.time}</th><th>${l.tokens}</th><th>${l.turns}</th><th>${l.changes}</th><th>${l.files}</th></tr></thead><tbody>${rows}</tbody></table></div></section>${judge}<section class="details"><div class="section-head"><h2>${l.details}</h2></div>${details}</section><footer class="footer"><span>${esc(l.generatedBy)}</span><span>${new Date(round.createdAt).toLocaleString(locale)}</span></footer></div>
</main><script>
(()=>{const decode=(value)=>{const binary=atob(value);const bytes=Uint8Array.from(binary,(char)=>char.charCodeAt(0));return new TextDecoder().decode(bytes)};const hydrate=(card)=>{if(card.dataset.loaded)return;const html=decode(card.dataset.artifactHtml||"");const frame=card.querySelector("iframe");const source=card.querySelector(".artifact-source");if(frame)frame.srcdoc=html;if(source)source.textContent=html;card.dataset.loaded="true"};document.addEventListener("toggle",(event)=>{const detail=event.target;if(!(detail instanceof HTMLDetailsElement)||!detail.open||!detail.classList.contains("contestant-detail"))return;const card=detail.querySelector(".artifact-preview");if(card)hydrate(card)},true);document.addEventListener("click",(event)=>{const target=event.target;if(!(target instanceof Element))return;const button=target.closest("[data-open-artifact]");if(!button)return;const card=button.closest(".artifact-preview");if(!card)return;hydrate(card);const html=decode(card.dataset.artifactHtml||"");const url=URL.createObjectURL(new Blob([html],{type:"text/html;charset=utf-8"}));window.open(url,"_blank","noopener");setTimeout(()=>URL.revokeObjectURL(url),60000)})})();
</script></body></html>`
}
