/** Build a self-contained, shareable PK battle report. */
import { getAgentLabel } from "@/lib/custom-agents"
import type { PkRound } from "@/stores/pk-arena-store"

function esc(raw: string): string {
  return raw
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
}

function formatMs(ms: number): string {
  const seconds = Math.round(ms / 1000)
  if (seconds < 60) return `${seconds}s`
  return `${Math.floor(seconds / 60)}m ${String(seconds % 60).padStart(2, "0")}s`
}

function diffStats(diff: string | null) {
  let added = 0
  let removed = 0
  for (const line of diff?.split("\n") ?? []) {
    if (line.startsWith("+") && !line.startsWith("+++")) added += 1
    if (line.startsWith("-") && !line.startsWith("---")) removed += 1
  }
  return { added, removed }
}

function renderDiff(diff: string | null, empty: string): string {
  if (!diff?.trim()) return `<p class="empty">${esc(empty)}</p>`
  return `<pre>${diff
    .split("\n")
    .map((line) => {
      const cls = line.startsWith("+")
        ? "add"
        : line.startsWith("-")
          ? "del"
          : line.startsWith("@@")
            ? "hunk"
            : ""
      return `<span class="line ${cls}">${esc(line || " ")}</span>`
    })
    .join("")}</pre>`
}

export function buildPkReportHtml(
  round: PkRound,
  filesBySlot: Record<string, string[]>,
  locale = "zh-CN"
): string {
  const zh = locale.toLowerCase().startsWith("zh")
  const l = zh
    ? {
        title: "智能体 PK 战报",
        status: "状态",
        finished: "已结束",
        running: "进行中",
        ready: "就绪",
        contestants: "参赛智能体",
        duration: "总用时",
        generated: "生成时间",
        ranking: "比赛结果",
        agent: "智能体",
        time: "用时",
        tokens: "输出 Token",
        turns: "轮次",
        changes: "代码变更",
        files: "文件",
        unavailable: "未提供",
        verdict: "裁判结论",
        details: "选手产出",
        outputFiles: "产出文件",
        diff: "代码 Diff",
        noFiles: "没有产出文件",
        noDiff: "没有可比较的代码变更",
        generatedBy: "由 Codeg 智能体 PK 竞技场生成",
      }
    : {
        title: "Agent PK Battle Report",
        status: "Status",
        finished: "Finished",
        running: "Running",
        ready: "Ready",
        contestants: "Contestants",
        duration: "Duration",
        generated: "Generated",
        ranking: "Results",
        agent: "Agent",
        time: "Time",
        tokens: "Output tokens",
        turns: "Turns",
        changes: "Code changes",
        files: "Files",
        unavailable: "Not reported",
        verdict: "Judge verdict",
        details: "Contestant output",
        outputFiles: "Output files",
        diff: "Code diff",
        noFiles: "No output files",
        noDiff: "No comparable code changes",
        generatedBy: "Generated by Codeg Agent PK Arena",
      }

  const finished = round.contestants.every((c) =>
    ["done", "error", "canceled"].includes(c.status)
  )
  const statusText = finished
    ? l.finished
    : round.status === "ready"
      ? l.ready
      : l.running
  const duration = round.contestants.reduce<number | null>(
    (max, c) => (c.durationMs == null ? max : Math.max(max ?? 0, c.durationMs)),
    null
  )
  const scores = [...(round.judgeResult?.scores ?? [])].sort(
    (a, b) => a.rank - b.rank
  )
  const scoreByAgent = new Map(scores.map((score) => [score.agentType, score]))

  const rows = round.contestants
    .map((c, index) => {
      const stat = diffStats(c.diff)
      const score = scoreByAgent.get(c.agentType)
      const files = filesBySlot[String(c.slot)] ?? []
      const tokenText = c.usage?.tokensReported
        ? c.usage.outputTokens.toLocaleString(locale)
        : l.unavailable
      return `<tr>
        <td class="rank">${score ? `#${score.rank}` : String(index + 1).padStart(2, "0")}</td>
        <td><b>${esc(getAgentLabel(c.agentType))}</b>${c.label ? `<small>${esc(c.label)}</small>` : ""}</td>
        <td>${score ? `<strong class="score">${score.score}</strong>` : "—"}</td>
        <td>${c.durationMs == null ? "—" : formatMs(c.durationMs)}</td>
        <td>${tokenText}</td>
        <td>${c.usage?.turnCount ?? "—"}</td>
        <td><span class="plus">+${stat.added}</span> <span class="minus">−${stat.removed}</span></td>
        <td>${files.length}</td>
      </tr>`
    })
    .join("")

  const judge = round.judgeResult
    ? `<section class="verdict">
        <div class="eyebrow">${l.verdict}</div>
        <h2>${esc(round.judgeResult.summary)}</h2>
        <div class="comments">${scores
          .map(
            (score) =>
              `<article><span>#${score.rank}</span><div><b>${esc(
                getAgentLabel(score.agentType)
              )} · ${score.score}</b><p>${esc(score.comment)}</p></div></article>`
          )
          .join("")}</div>
      </section>`
    : ""

  const details = round.contestants
    .map((c) => {
      const files = filesBySlot[String(c.slot)] ?? []
      return `<details>
        <summary><span>${esc(getAgentLabel(c.agentType))}${c.label ? ` · ${esc(c.label)}` : ""}</span><span>${l.outputFiles} ${files.length} · ${l.diff}</span></summary>
        <div class="detail-grid">
          <div><h3>${l.outputFiles}</h3>${
            files.length
              ? `<ul>${files.map((file) => `<li>${esc(file)}</li>`).join("")}</ul>`
              : `<p class="empty">${l.noFiles}</p>`
          }</div>
          <div><h3>${l.diff}</h3>${renderDiff(c.diff, l.noDiff)}</div>
        </div>
      </details>`
    })
    .join("")

  return `<!doctype html>
<html lang="${esc(locale)}"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>${esc(l.title)} · ${esc(round.task)}</title>
<style>
:root{--ink:#11110f;--paper:#f3f0e8;--card:#fffdf7;--line:#d8d2c5;--accent:#ffd84d;--muted:#6b675e;--green:#087b45;--red:#b42318}*{box-sizing:border-box}body{margin:0;background:#ddd8cc;color:var(--ink);font:14px/1.55 Inter,-apple-system,BlinkMacSystemFont,"Segoe UI","PingFang SC",sans-serif}.sheet{width:min(1180px,100%);margin:32px auto;background:var(--paper);box-shadow:0 24px 80px #302b2050}.masthead{position:relative;overflow:hidden;background:var(--ink);color:#fff;padding:52px 56px 46px}.masthead:after{content:"PK";position:absolute;right:22px;bottom:-82px;font:900 220px/1 Arial;color:#ffffff0b;letter-spacing:-20px}.brand{display:flex;align-items:center;gap:12px;font-size:12px;font-weight:700;letter-spacing:.16em;text-transform:uppercase}.brand i{display:block;width:28px;height:5px;background:var(--accent)}h1{position:relative;max-width:900px;margin:56px 0 42px;font-size:clamp(34px,5vw,68px);line-height:1.04;letter-spacing:-.045em}.meta{position:relative;display:grid;grid-template-columns:repeat(4,1fr);gap:24px;border-top:1px solid #ffffff28;padding-top:22px}.meta span{display:block;color:#aaa79f;font-size:11px;text-transform:uppercase;letter-spacing:.08em}.meta b{display:block;margin-top:3px;color:#fff;font-size:15px;letter-spacing:0}.content{padding:42px 56px 64px}.section-head{display:flex;align-items:end;justify-content:space-between;margin:0 0 14px}.section-head h2{margin:0;font-size:22px;letter-spacing:-.02em}.section-head span,.eyebrow{font-size:11px;font-weight:800;letter-spacing:.14em;text-transform:uppercase;color:var(--muted)}.table-wrap{overflow:auto;border:1px solid var(--line);background:var(--card)}table{width:100%;border-collapse:collapse;min-width:820px}th,td{padding:15px 14px;border-bottom:1px solid var(--line);text-align:left;white-space:nowrap}th{background:#ebe6da;color:var(--muted);font-size:10px;letter-spacing:.08em;text-transform:uppercase}tr:last-child td{border-bottom:0}.rank{font:800 18px ui-monospace,monospace}.score{display:inline-grid;place-items:center;min-width:42px;padding:3px 8px;background:var(--accent);font-size:17px}td small{display:block;color:var(--muted)}.plus{color:var(--green)}.minus{color:var(--red)}.verdict{margin:42px 0;padding:34px;border:1px solid var(--ink);background:var(--card)}.verdict h2{max-width:900px;margin:10px 0 26px;font-size:25px;line-height:1.35}.comments{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));gap:12px}.comments article{display:flex;gap:12px;border-top:1px solid var(--line);padding-top:14px}.comments article>span{font:800 18px ui-monospace,monospace}.comments p{margin:5px 0 0;color:var(--muted)}.details{margin-top:42px}details{border-top:1px solid var(--line);background:var(--card)}details:last-child{border-bottom:1px solid var(--line)}summary{display:flex;justify-content:space-between;gap:20px;padding:18px 20px;cursor:pointer;font-weight:700}summary span:last-child{color:var(--muted);font-size:12px;font-weight:500}.detail-grid{display:grid;grid-template-columns:minmax(220px,.35fr) minmax(0,1fr);gap:24px;border-top:1px solid var(--line);padding:20px}.detail-grid h3{margin:0 0 10px;font-size:12px;text-transform:uppercase;letter-spacing:.08em}.detail-grid ul{margin:0;padding-left:18px;word-break:break-all}.empty{color:var(--muted)}pre{max-height:560px;margin:0;overflow:auto;background:#171715;color:#d7d3ca;padding:16px;font:11px/1.55 ui-monospace,SFMono-Regular,Menlo,monospace}.line{display:block;white-space:pre}.line.add{background:#0c7b4530;color:#a9e6c5}.line.del{background:#b4231833;color:#ffb4ab}.line.hunk{color:#ffd84d}.footer{display:flex;justify-content:space-between;border-top:1px solid var(--line);margin-top:42px;padding-top:18px;color:var(--muted);font-size:12px}@media(max-width:720px){.sheet{margin:0}.masthead,.content{padding-left:22px;padding-right:22px}h1{margin:38px 0 30px}.meta{grid-template-columns:1fr 1fr}.detail-grid{grid-template-columns:1fr}.footer{display:block}}@media print{body{background:#fff}.sheet{width:100%;margin:0;box-shadow:none}details{break-inside:avoid}.masthead{-webkit-print-color-adjust:exact;print-color-adjust:exact}}
</style></head><body><main class="sheet">
<header class="masthead"><div class="brand"><i></i>Codeg · ${esc(l.title)}</div><h1>${esc(round.task)}</h1><div class="meta"><div><span>${l.status}</span><b>${statusText}</b></div><div><span>${l.contestants}</span><b>${round.contestants.length}</b></div><div><span>${l.duration}</span><b>${duration == null ? "—" : formatMs(duration)}</b></div><div><span>${l.generated}</span><b>${new Date().toLocaleString(locale)}</b></div></div></header>
<div class="content"><section><div class="section-head"><h2>${l.ranking}</h2><span>ROUND ${round.id}</span></div><div class="table-wrap"><table><thead><tr><th>#</th><th>${l.agent}</th><th>Score</th><th>${l.time}</th><th>${l.tokens}</th><th>${l.turns}</th><th>${l.changes}</th><th>${l.files}</th></tr></thead><tbody>${rows}</tbody></table></div></section>${judge}<section class="details"><div class="section-head"><h2>${l.details}</h2></div>${details}</section><footer class="footer"><span>${esc(l.generatedBy)}</span><span>${new Date(round.createdAt).toLocaleString(locale)}</span></footer></div>
</main></body></html>`
}
